
description: Energym Preference Data

target:
  service: sing
  name: msrresrchvc
  vc: gcr-singularity-resrch

environment:
  image: energym_gcr:sing2
  registry: resrchvc4cr.azurecr.io # any public registry can be specified here
  username: resrchvc4cr
  setup:
    - apt-get update

code:
  local_dir: $CONFIG_DIR/

data:
  local_dir: $CONFIG_DIR/data/
  remote_dir: energym/v2/

jobs:

- name: SeminarcenterThermostat-v0-preference_data--round_0-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 0 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_0-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 0 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_0-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 0 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_0-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 0 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_1-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 1 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_1-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 1 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_1-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 1 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_1-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 1 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_2-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 2 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_2-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 2 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_2-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 2 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_2-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 2 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_3-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 3 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_3-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 3 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_3-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 3 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_3-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 3 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_4-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 4 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_4-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 4 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_4-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 4 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_4-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 4 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_5-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 5 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_5-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 5 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_5-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 5 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_5-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 5 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_6-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 6 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_6-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 6 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_6-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 6 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_6-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 6 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_7-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 7 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_7-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 7 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_7-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 7 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterThermostat-v0-preference_data--round_7-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterThermostat-v0 --amlt  --round 7 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_0-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 0 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_0-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 0 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_0-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 0 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_0-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 0 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_1-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 1 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_1-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 1 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_1-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 1 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_1-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 1 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_2-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 2 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_2-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 2 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_2-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 2 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_2-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 2 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_3-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 3 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_3-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 3 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_3-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 3 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_3-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 3 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_4-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 4 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_4-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 4 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_4-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 4 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_4-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 4 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_5-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 5 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_5-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 5 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_5-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 5 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_5-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 5 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_6-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 6 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_6-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 6 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_6-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 6 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_6-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 6 --idx 15,16,17,18,19 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_7-idx_0,1,2,3,4
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 7 --idx 0,1,2,3,4 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_7-idx_5,6,7,8,9
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 7 --idx 5,6,7,8,9 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_7-idx_10,11,12,13,14
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 7 --idx 10,11,12,13,14 --device cuda:0

- name: SeminarcenterFull-v0-preference_data--round_7-idx_15,16,17,18,19
  sku: G1
  command:
  - python preference_data.py --building SeminarcenterFull-v0 --amlt  --round 7 --idx 15,16,17,18,19 --device cuda:0
