description: Energym Train Bulk Online RL

target:
  # service: sing
  # name: msrresrchvc
  # vc: gcr-singularity-resrch
  service: amlk8s
  name: ms-shared
  vc: MS-Shared
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  # name: msrresrchvc
  # vc: gcr-singularity-resrch

environment:
  image: energym_sing:sing
  registry: resrchvc4cr.azurecr.io # any public registry can be specified here
  username: resrchvc4cr
  setup:
    - apt-get update && apt-get install --no-install-recommends --no-install-suggests -yq figlet && rm -rf /var/lib/apt/lists/* && apt-get purge --auto-remove && apt-get clean && figlet Singularity
    - apt install libffi-dev


code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

data:
  local_dir: $CONFIG_DIR/data/
  remote_dir: energym/

# list of jobs to run, we run 2 jobs in this example

# buildings_list = ["ApartmentsThermal-v0", "ApartmentsGrid-v0", "Apartments2Thermal-v0",
#                   "Apartments2Grid-v0", "OfficesThermostat-v0", "MixedUseFanFCU-v0",
#                   "SeminarcenterThermostat-v0", "SeminarcenterFull-v0", "SimpleHouseRad-v0",
#                   "SimpleHouseRSla-v0", "SwissHouseRSlaW2W-v0", "SwissHouseRSlaTank-v0"] 


jobs:
- name: ApartmentsThermal-v0
  sku: G1
  command:
  - python train_bulk.py --building ApartmentsThermal-v0 --amlt --seed 7,13,17,19,23,37,53,71

- name: ApartmentsGrid-v0
  sku: G1
  command:
  - python train_bulk.py --building ApartmentsGrid-v0 --amlt --seed 7,13,17,19,23,37,53,71

- name: Apartments2Thermal-v0
  sku: G1
  command:
  - python train_bulk.py --building Apartments2Thermal-v0 --amlt --seed 7,13,17,19,23,37,53,71

- name: Apartments2Grid-v0
  sku: G1
  command:
  - python train_bulk.py --building Apartments2Grid-v0 --amlt --seed 7,13,17,19,23,37,53,71

- name: OfficesThermostat-v0
  sku: G1
  command:
  - python train_bulk.py --building OfficesThermostat-v0 --amlt --seed 7,13,17,19,23,37,53,71

- name: MixedUseFanFCU-v0
  sku: G1
  command:
  - python train_bulk.py --building MixedUseFanFCU-v0 --amlt --seed 7,13,17,19,23,37,53,71

- name: SeminarcenterThermostat-v0
  sku: G1
  command:
  - python train_bulk.py --building SeminarcenterThermostat-v0 --amlt --seed 7,13,17,19,23,37,53,71
  

# - name: SimpleHouseRad-v0
#   sku: G1
#   command:
#   - python train_bulk.py --building SimpleHouseRad-v0 --amlt --seed 7,13,17,19,23,37,53,71

# - name: SimpleHouseRSla-v0
#   sku: G1
#   command:
#   - python train_bulk.py --building SimpleHouseRSla-v0 --amlt --seed 7,13,17,19,23,37,53,71

# - name: SwissHouseRSlaW2W-v0
#   sku: G1
#   command:
#   - python train_bulk.py --building SwissHouseRSlaW2W-v0 --amlt --seed 7,13,17,19,23,37,53,71

# - name: SwissHouseRSlaTank-v0
#   sku: G1
#   command:
#   - python train_bulk.py --building SwissHouseRSlaTank-v0 --amlt --seed 7,13,17,19,23,37,53,71
